### ISSUE TITLE
Layout Broken when Next/Previous Link Clicked

### ISSUE THREAD

**Issue by AshrafAlam** [cvluca/gatsby-starter-markdown#1]
![image](https://user-images.githubusercontent.com/167864/53612136-1d475900-3c0c-11e9-8e32-e9db25dbc89b.png)

**Comment by cvluca** [comment]
Yeah, it seems the problem only happens in the demo. I am trying to fix it.

**Comment by AshrafAlam** [comment]
Thanks @cvluca . Good work so far.

**Comment by cvluca** [comment]
fixed
