### ISSUE TITLE
State update during render bug

### ISSUE THREAD

**Issue by lxieyang** [cvluca/gatsby-starter-markdown#10]
I always get the following warning in the console:
![Screen Shot 2019-03-12 at 4 04 00 PM](https://user-images.githubusercontent.com/16089305/54232307-b6b21d00-44e0-11e9-9f51-17e88fa116e3.png)
I think the problem is in `Layout.js`. You called `setPostPageOn` and other state-changing methods in `render()`.

I do think this is an urgent issue, so if you could help fix it asap, it would be great! Thank you!

**Comment by cvluca** [comment]
@lxieyang fixed.
