### ISSUE TITLE
The sidebar does not display properly when directly visiting the docs pages

### ISSUE THREAD

**Issue by lxieyang** [cvluca/gatsby-starter-markdown#11]
Hi, great fix on the warning bug last time! Thanks!

However, I found that the sidebar does not display properly when you directly go to a url of one of the docs pages (or you could go there and then refresh). Would you have some time to fix this? It kind of breaks the UX of the site. But it should be an easy fix!

Thanks again!

![ezgif-4-9c0e475ded29](https://user-images.githubusercontent.com/16089305/54368111-f21c2b00-4649-11e9-91c3-d3cd8d0554d0.gif)

**Comment by cvluca** [comment]
@lxieyang same issue as #1 , I am not quite sure why that happened yet since the problem only occurs in the demo. It is probably the compiler did something for me when I run it locally, but not in build.

**Comment by lxieyang** [comment]
I fixed it by "re-rendering" the site upon the initial visit. It's not exactly a good practice but apparently, we have to do something about it until the Gatsby team fix the compiler.

**Comment by adueck** [comment]
First of all let me say that I *love* the design of this! (Especially the docs page/sidebar. It's beautiful) Good work so far!

But I am having this problem when 'refreshing' on the docs page or visiting it directly. It comes out looking like this.  

<img width="949" alt="Screenshot 2019-04-08 18 23 33" src="https://user-images.githubusercontent.com/12955501/55731662-a2076d00-5a2b-11e9-9ca0-67bc3136afaf.png">

Also, the blue navbar at the top flashes on every page change and comes up late in the initial page load...

**Comment by cvluca** [comment]
fixed
