### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ewirth** [cvluca/gatsby-starter-markdown#12]
See the attached image:
![image](https://user-images.githubusercontent.com/11816204/54541962-cf17b100-4992-11e9-814a-1b4094071f6e.png)

**Comment by cvluca** [comment]
@ewirth Those are just some warnings. I think this should be fine. Did you get any error messages? You should better check on [Gatsby site](https://www.gatsbyjs.org/docs/gatsby-on-windows/).
