### ISSUE TITLE
pathPrefix not working

### ISSUE THREAD

**Issue by joaorsfonseca** [cvluca/gatsby-starter-markdown#14]
I'm trying to use the pathPrefix on gatsby-config but it seems that isn't working.

`pathPrefix: "/arqui-docs",`

I've build it using the command
`gatsby build --prefix-paths`

the start page seems to be working properly
![image](https://user-images.githubusercontent.com/33959685/54603845-47d34780-4a3d-11e9-81fe-b16d3db0ca64.png)

Bbut after navigate to any o the links, the sidebar doesn't shows anything :(
![image](https://user-images.githubusercontent.com/33959685/54603919-705b4180-4a3d-11e9-9f24-cb10ac11d4ab.png)

Am I missing something?

Thanks.

**Comment by cvluca** [comment]
@joaorsfonseca my bad. I didn't handle the prefixpath nicely. Should work now!

**Comment by joaorsfonseca** [comment]
@cvluca how do i update the source code withtou losing all the changes i already made on my md files mainly :)
