### ISSUE TITLE
the navBar is always rerender by click menuItem

### ISSUE THREAD

**Issue by wulucxy** [cvluca/gatsby-starter-markdown#2]
what I expect is：

when I clicked the menuItem，navBar should not be rerender。

**Comment by cvluca** [comment]
Sidebar and anchor only appear on the post pages. I am thinking to make them optional, and it's in my todo list.

**Comment by wulucxy** [comment]
@cvluca hi，what‘s the progress now？

**Comment by cvluca** [comment]
@wulucxy probably will do it this weekend, if I have time

**Comment by lxieyang** [comment]
It'd be awesome if you could get it fixed! I really love everything else about it!

**Comment by lxieyang** [comment]
It turned out it's an easy fix. Changing the `sizeMe({ monitorHeight: true })` in `Header.js` to `sizeMe({ monitorHeight: true, refreshMode: 'debounce', noPlaceholder: true })` should fix the refreshing bug.
@wulucxy would you check if this solution works? Thanks so much!

**Comment by wulucxy** [comment]
@lxieyang it works。what happened to it。🤣🤣

**Comment by wulucxy** [comment]
@lxieyang it's a great starter，but I think @cvluca do much more than I need。

I don't need `redux`，`react-sizeme`，so may be I will fork it，and remove the things I don't want。
