### ISSUE TITLE
example with images

### ISSUE THREAD

**Issue by brambow** [cvluca/gatsby-starter-markdown#7]
Could you add an example article/post (e.g. Quick Start) that includes an image? Including images in the contents folder alongside the markdown doesn't seem to work. Gatsby is looking for a page instead of an image. Is there a designated directory to add images that will be referenced in markdown?

![image](https://user-images.githubusercontent.com/6227786/53960178-9125ad80-40b3-11e9-97ad-bb9dc21f8908.png)

**Comment by brambow** [comment]
Got it. Needed to add 'gatsby-remark-images' to the project and then include it as a plugin under 'gatsby-transformer-remark' in gatsby-config.js.

**Comment by cvluca** [comment]
@brambow There are many plugins for remark available and they haven't been added into this starter. I will add more examples of different use cases. Thanks for your suggestion.

**Comment by joaorsfonseca** [comment]
@brambow can you specigy how did you included the image directly on .md file? Also, where should i add the image file?

Thanks.

**Comment by brambow** [comment]
@joaorsfonseca markdown syntax for adding an image is like ![placeholder/alt text](path/to/image.png)

You can also use HTML syntax for images in markdown, but using the gatsby-remark-images plugin like I did in the PR that just got merged is a more consistent way to manage image sizes, etc.

**Comment by joaorsfonseca** [comment]
My md file looks like this, the project structure is also visible.

![image](https://user-images.githubusercontent.com/33959685/54606147-e31aeb80-4a42-11e9-9756-002a45aa8958.png)

Is the link src/images/non-billable-hours.png correct?
